### ISSUE TITLE
Module inclusion suggestion

### ISSUE THREAD

**Issue by R3Ked** [AndrioCelos/KtaneSouvenir#10]
I suggest Wire Ordering to be included in Souvenier. On the repository, it says that Wire Ordering is not a candidate for inclusion. I suggest this is changed. When the module is solved, the colors and numbers disappear. I suggest that Souvenier asks about the order of wires cut, the color of the wires, the color of the displays, and the numbers on the displays.

**Comment by AndrioCelos** [comment]
Some research reveals that the feature of hiding the colours and numbers was added to Wire Ordering _after_ it was marked as not a candidate. As such, I may overrule that evaluation.

**Comment by R3Ked** [comment]
ah ok
